### ISSUE TITLE
Exception handler: Object of class stdClass could not be converted to string

### ISSUE THREAD

**Issue by cweiske** [RatkoR/laravel-crate.io#11]
When crate crashes an `Illuminate\Database\QueryException` is created. This class tries to generate a helpful message that includes the SQL statement in `formatMessage`:

    return $previous->getMessage().' (SQL: '.Str::replaceArray('?', $bindings, $sql).')';

This totally breaks when one of the attributes is an object, leading to a new exception:

> Object of class stdClass could not be converted to string

If `\RatkoR\Crate\Connection` would override `runQueryCallback` then it could instantiate its own `QueryException` there.

---- 

Crate crashed here with a "SQLActionException[NullPointerException in io.crate.analyze.ConstraintsValidator.validate(ConstraintsValidator.java:36)]". I've got no idea how to force such a crash or error within crate itself.

**Comment by RatkoR** [comment]
Yes yes, something like https://github.com/RatkoR/laravel-crate.io/pull/12/files?

**Comment by RatkoR** [comment]
Commited in 5184db6

**Comment by cweiske** [comment]
Related: https://github.com/crate/crate/issues/4594
