### ISSUE TITLE
Install with Laravel 5.4

### ISSUE THREAD

**Issue by web64** [RatkoR/laravel-crate.io#14]
The project looks great and I would like to try it out, but at the moment it won't install with Laravel 5.4.
Any chance of updating this?

**Comment by RatkoR** [comment]
Sure, I'll take a look!

Btw, you can create a PR If you're fluent in PHP and if it's not to broken. Otherwise I'll try to fix it next week.

**Comment by RatkoR** [comment]
Fixed with #15.
