### ISSUE TITLE
Incompatible Issue on Laravel 5.6

### ISSUE THREAD

**Issue by yusuf-yak** [RatkoR/laravel-crate.io#22]
Hello,

when i try to run migration on Laravel 5.6 i get the below compatibility error.

**Declaration of RatkoR\Crate\Schema\Blueprint::addImpliedCommands() should be compatible with Illuminate\Database\Schema\Blueprint::addImpliedCommands(Illuminate\Database\Schema\Grammars\Grammar $grammar).**

**See the migration file below.**
```
<?php

use Illuminate\Support\Facades\Schema;
//use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use RatkoR\Crate\Schema\Blueprint as Blueprint;

class CratedbCreateTableBadEvents extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::connection('crate')->create('tableName', function(Blueprint $table)
        {
            $table->string('app_id');
            $table->objectField('error','object as (bytes_limit integer, bytes_wanted integer)');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::connection('crate')->dropIfExists('tableName');
    }
}
```

**Please help look into this.**

Thanks,
Yusuf Yak.

**Comment by RatkoR** [comment]
Which version of laravel do you have 5.6.?

**Comment by yusuf-yak** [comment]
Laravel version 5.6.39

We finally decided to upgrade to Laravel 5.7.*

**Comment by RatkoR** [comment]
Upgrade is even better, because the new package (7.0.0) works with laravel 5.7.
