### ISSUE TITLE
Incompatibility Issue for Laravel 5.2

### ISSUE THREAD

**Issue by axelex** [RatkoR/laravel-crate.io#4]
Hello,

I've found this incompatibility issue due to some changes made in Laravel 5.2 to the Illuminate\Database\Connection::setFetchMode($fetchMode, $fetchArgument = NULL, array $fetchConstructorArgument = Array) method which has now more than one parameters: 

ErrorException in Connection.php line 13:
Declaration of RatkoR\Crate\Connection::setFetchMode() should be compatible with Illuminate\Database\Connection::setFetchMode($fetchMode, $fetchArgument = NULL, array $fetchConstructorArgument = Array)

I've added the parameters to the method in RatkoR\Crate\Connection::setFetchMode() and ran some queries after that and it worked, but I would like to be able to make updates to crate driver without having to make this change every time I instal the project.

If there's no other solution can you add that in the documentation as a change that will need to be made for Laravel 5.2 and if you have a different solution can you let me know as soon as you can?

Thanks!

**Comment by axelex** [comment]
Is anybody still taking care of issues here?

**Comment by RatkoR** [comment]
Hi,

yes, we are. We'll look into this on monday.
Sorry, we've been busy with some other stuff - use your hack until we release a new version.

Thank you

**Comment by RatkoR** [comment]
We added a new version that works ok with laravel 5.2.15. Can you test please?
(Version_ 2.\* is for new laravels (5.2.15 or more), version 1.0 is for older ones.)

I'll close the ticket if it works with you now.

Thx,

**Comment by axelex** [comment]
It works now. Thanks a lot!
