### ISSUE TITLE
Cannot use any(), match() and other crate operators

### ISSUE THREAD

**Issue by axelex** [RatkoR/laravel-crate.io#6]
Could you add any(), match() and other operators that are used in crate or if it's already possible to do that somehow please let me know.

Thank you!

**Comment by RatkoR** [comment]
Well, the whereRaw() expression could probably be used here.

Something like:

```
Locations::whereRaw("'netball' = ANY(race['interests'])")->get()
```

if we follow the example at [Crate](https://crate.io/docs/reference/sql/queries.html#any-array).

**Comment by RatkoR** [comment]
Please open this ticket again if `whereRaw()` doesn't work for you. Thank you.
